server {
    server_name liujiayin.me www.liujiayin.me;

    root /var/www/liujiayin.me/www;
    index index.html;

    access_log /var/log/nginx/liujiayin.me.access.log main;
    error_log  /var/log/nginx/liujiayin.me.error.log warn;
}
