server {
    server_name liumuxi.me www.liumuxi.me;

    root /var/www/liumuxi.me/www;
    index index.html;

    access_log /var/log/nginx/liumuxi.me.access.log main;
    error_log  /var/log/nginx/liumuxi.me.error.log warn;
}
