server {
    server_name freshrss.liuchao.me;

    root /var/www/liuchao.me/freshrss/p/;
    index index.php index.html index.htm;

    access_log /var/log/nginx/freshrss.liuchao.me.access.log main;
    error_log  /var/log/nginx/freshrss.liuchao.me.error.log warn;
    error_page 404 https://404.liuchao.me/;

    location ~ ^.+?\.php(/.*)?$ {
        fastcgi_pass unix:/run/php/php8.4-fpm.sock;
	fastcgi_split_path_info ^(.+\.php)(/.*)$;
	# By default, the variable PATH_INFO is not set under PHP-FPM
	# But FreshRSS APIs greader.php and misc.php need it. If you have a “Bad Request” error, double check this var!
	# NOTE: the separate $path_info variable is required. For more details, see:
	# https://trac.nginx.org/nginx/ticket/321
	set $path_info $fastcgi_path_info;
	fastcgi_param PATH_INFO $path_info;
	include fastcgi_params;
	fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location / {
        try_files $uri $uri/ /index.php?$args;
    }
    
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/liuchao.me/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/liuchao.me/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = freshrss.liuchao.me) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name freshrss.liuchao.me;
    return 404; # managed by Certbot


}
